# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c8564fb5c5e14c6fe74d795eb6c9c94dc3111e72adc6a6c0196c1e323604403de06d91c3daee034ca12e4002a84e1bd24f20539036d75b91e9397dd54806a43

test:
  secret_key_base: 0113155eec3efab89985b1c0d110f9f869f160215d9b7d1dc4d17b285b887f9e5d14398dccba816fc40cb2e684535fb43daa4b6f494f0b9a2e15bc0284fc8784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
